# Generated by Django 4.1.5 on 2023-02-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
