# Generated by Django 4.1.6 on 2023-02-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
