# Generated by Django 4.1.6 on 2023-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
