# Generated by Django 4.1.6 on 2023-02-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0009_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
