# Generated by Django 4.1.6 on 2023-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0011_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photos'),
        ),
    ]
