# Generated by Django 4.1.6 on 2023-02-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0012_remove_profile_profile_picture_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
