# Generated by Django 4.1.6 on 2023-02-13 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BetterYou', '0013_remove_profile_bio_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointement',
            new_name='Appointment',
        ),
    ]
