# Generated by Django 4.1.6 on 2023-02-14 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0014_rename_appointement_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime.now, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Web Developpement', 'Web Developpement'), ('AI Developpement', 'AI Developpement'), ('APP Development', 'APP Development')], default='AI Developpement', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[('09:00 AM ', '09:00 AM '), ('09:40 AM ', '09:40 AM '), ('10:20 AM ', '10:20 AM '), ('11:40 AM ', '11:40 AM '), ('13:30 PM ', '13:30 PM '), ('14:10 PM ', '14:10 PM '), ('14:50 PM ', '14:50 PM '), ('15:30 pm ', '15:30 pm '), ('16:10 pm ', '16:10 pm '), ('16:50 pm ', '16:50 pm ')], default='09:00 AM', max_length=30),
        ),
    ]
