# Generated by Django 4.1.6 on 2023-02-14 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0016_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('APP Development', 'APP Development'), ('AI Development', 'AI Development')], default='Doctor care', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00 AM ', '09:00 AM '), ('09:40 AM ', '09:40 AM '), ('10:20 AM ', '10:20 AM '), ('11:40 AM ', '11:40 AM '), ('13:30 PM ', '13:30 PM '), ('14:10 PM ', '14:10 PM '), ('14:50 PM ', '14:50 PM '), ('15:30 pm ', '15:30 pm '), ('16:10 pm ', '16:10 pm '), ('16:50 pm ', '16:50 pm ')], default='3 PM', max_length=10),
        ),
    ]
