# Generated by Django 4.1.6 on 2023-02-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterYou', '0018_alter_appointment_service_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00 ', '09:00 '), ('09:40 ', '09:40 '), ('10:20 ', '10:20 '), ('11:40 ', '11:40 '), ('13:30 ', '13:30 '), ('14:10 ', '14:10 '), ('14:50 ', '14:50 '), ('15:30 ', '15:30 '), ('16:10 ', '16:10 '), ('16:50 ', '16:50 ')], default='09:00', max_length=10),
        ),
    ]
